name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      run: |
        echo "Deployment step placeholder"
        # In a real-world scenario, you would replace the above line with commands to deploy your application.
        # For example, using a cloud provider's CLI to push a Docker image or sync files.
      
